### ISSUE TITLE
Migrate Commands from Prefix to Slash

### ISSUE THREAD

**Issue by Zemerik** [BlobDeveloper/discord-giveaways-bot#2]
Slash commands make your bot easier to use and work as an automatic help menu for your bot. Adding Slash Commands, will gain your bot more reach, which may also result in more contributors. Additionally, verified Discord Bots also require Slash Commands. 

If you want, I am free to work on this issue. 

Regards, 
Zemerik

**Comment by BlobDeveloper** [comment]
ok? :DD
